project:
  type: book
  output-dir: _site
  resources:
    - "/.nojekyll"

book:
  title: "Dashboards: Using R to create actionable science"
  subtitle: "Quarto & Shiny 1-Day Workshop for CERF Conference (2023-11-12)"
  author: "Ben Best, Marcus Beck, Tylar Murray, Enrique Montes"
  date: today
  date-format: "YYYY-MM-DD"
  chapters:
    - index.qmd
    - intro.qmd
    - quarto.qmd
    - shiny.qmd
    - summary.qmd
    - ui_design.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt
  #   prefer-html: true

