project:
  type: book
  output-dir: _site
  resources:
    - "/.nojekyll"

book:
  title: "Dashboards: Using R to create actionable science"
  subtitle: "Quarto & Shiny 1-Day Workshop for CERF Conference (2023-11-12)"
  author: "Ben Best, Marcus Beck, Tylar Murray, Enrique Montes"
  repo-url: https://github.com/tbep-tech/shiny-workshop
  reader-mode: true
  repo-actions: [edit]
  search: true
  date: today
  date-format: "YYYY-MM-DD"
  page-footer:
    left: |
      Website created by authors, with attribution to external content
    right: |
      This book was built with <a href="https://quarto.org/" target="_blank">Quarto</a>
  chapters:
    - index.qmd
    - intro.qmd
    - quarto.qmd
    - shiny.qmd
    - summary.qmd
    - ui_design.qmd
    - references.qmd
  appendices:
    - setup.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
    css: libs/style.css
    code-tools:
      source: repo
  # pdf:
  #   documentclass: scrreprt
  #   prefer-html: true

