project:
  type: book
  output-dir: _site
  resources:
    - "/.nojekyll"

book:
  title: "Dashboards: Using R to create actionable science"
  subtitle: "Quarto & Shiny: CERF 1-Day Workshop, Nov. 12th, 2023"
  author: "Ben Best, Marcus Beck, Tylar Murray, Enrique Montes"
  repo-url: https://github.com/tbep-tech/shiny-workshop
  reader-mode: true
  repo-actions: [edit]
  search: true
  date: today
  date-format: "YYYY-MM-DD"
  page-navigation: true
  page-footer:
    left: |
      Website created by instructors, with attribution to external content
    right: |
      This book was built with <a href="https://quarto.org/" target="_blank">Quarto</a>
  chapters:
    - index.qmd
    - part: "Modules"
      chapters:
        - intro.qmd
        - quarto.qmd
        - shiny.qmd
        - ui_design.qmd
    - part: resources.qmd
      chapters:
        - resources/useful.qmd
        - resources/tbepwq.qmd
        - resources/tbepsg.qmd
        - resources/tbepbt.qmd
        - resources/tbeptc.qmd
        - resources/tbepnk.qmd
        - resources/tbeplu.qmd
        - resources/tbeppp.qmd
        - resources/tbepsc.qmd
        - resources/fl_wq_dash.qmd
        - resources/nms_climate_dash.qmd
        - resources/obisindicators.qmd
        - resources/rocky_shore_dash.qmd
        - resources/seascapes.qmd
  appendices:
    - setup.qmd
    - rintro.qmd
    - addlquarto.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
    css: libs/style.css
    code-tools:
      source: repo
    toc-depth: 4
  # pdf:
  #   documentclass: scrreprt
  #   prefer-html: true

